# Etapa 1 - build
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /app
COPY . .
RUN mvn clean package -DskipTests

# Etapa 2 - runtime
FROM eclipse-temurin:21-jdk
WORKDIR /app
COPY --from=build /app/target/*-runner.jar app.jar

EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
